### PR TITLE
Add PHP 7.1 Support

### LINKED ISSUE #58: No more support for PHP 7.1?
I'm currently using PHP 7.1 and Laravel 5.8, however version 0.0.6 and above only supports PHP 7.2 for Laravel v6.0. Is it possible to include PHP 7.1 for those with Laravel 5.x?

### PR DESCRIPTION
**Pull request by irazasyed**
Closes #58

### CODE REVIEW

**Comment by irazasyed** [comment]
@atymic Could you please take a look at this? Not sure why the build is failing.

**Comment by atymic** [comment]
> @atymic Could you please take a look at this? Not sure why the build is failing.

Looks like PHP unit 8 doesn't support PHP 7.1

**Comment by atymic** [comment]
The issues is it's using the global phpunit version:
```
0.09s$ ./vendor/bin/phpunit --version
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

0.49s$ phpunit --coverage-text --coverage-clover=coverage.clover
PHPUnit 8.0.2 by Sebastian Bergmann and contributors.
```

Will push a fix to the branch.

**Comment by irazasyed** [comment]
@atymic Good catch. Thanks. 

I think we should update the skeleton with these changes too. They use global phpunit as well.

**Comment by atymic** [comment]
Good idea. I'll fix that, thanks.

**Pull request merged**
