### PR TITLE
use laravel Conditionable trait

### PR DESCRIPTION
**Pull request by foremtehan**
Added laravel Conditionable trait, It allows to use `when` on methods chain like: 

```php
TelegramMessage::create()
    ->content('body')
    ->when($condition, fn(TelegramMessage $telegram) => $telegram->buttonWithCallback('button', 123))
    ->button('button', 'url');
```

### CODE REVIEW

**Comment by foremtehan** [comment]
we do support `"illuminate/support": "5.5 - 9"` but this trait not exists before version 8, what we should do now ?

**Comment by irazasyed** [comment]
Thanks for the PR. 

Please add tests for this. 

Also, we can drop support for older versions prior to v8 of Laravel and release a major version of this package. I'll look into this shortly.

**Comment by foremtehan** [comment]
Done.

**Comment by irazasyed** [comment]
Thank you!

**Pull request merged**
