### PR TITLE
test on php 7.4

### PR DESCRIPTION
**Pull request by sergiy-petrov**

### CODE REVIEW

**Comment by sergiy-petrov** [comment]
seems some tests needs to be updated

**Comment by irazasyed** [comment]
Could you please fix the issues and I'll merge this?

**Comment by sergiy-petrov** [comment]
@irazasyed it was because of outdated mockery version. 
See https://github.com/mockery/mockery/pull/980
It was fixed in 1.2.3 but I've updated it to ^1.3 in composer.json

I've also renamed class name to be consistent with test file name and target class.

**Comment by irazasyed** [comment]
Thank you @sergiy-petrov

**Pull request merged**
