### PR TITLE
send notification to multiple receivers

### PR DESCRIPTION
**Pull request by faissaloux**
Hello 👋🏻

I've made this PR so we can send notification to multiple receivers by separating chatIds by a comma in ```to()``` method

Examples:

```
TelegramMessage::create()
            ->to($receiver1, $receiver2)
            ->content("Hello there!");
```

```
TelegramFile::create()
        ->to($receiver1, $receiver2)
        ->content('Hello there!')
        ->file($photo, 'photo');
```

```
TelegramLocation::create()
        ->to($receiver1, $receiver2)
        ->latitude($latitude)
        ->longitude($longitude);
```

### CODE REVIEW

**Comment by irazasyed** [comment]
Hello,

Thanks for the PR.

1. Wouldn't this hit the rate limitations with Telegram since there is no interval between each message?

2. How is this any better than making use of the Notification facade that already supports [multiple notifiable entities](https://laravel.com/docs/8.x/notifications#using-the-notification-facade)? You can send to multiple recipients that way.

**Comment by faissaloux** [comment]
@irazasyed
1. I can add a sleep(1) so we can guarantee one request/s.
2. To use this we need Model using ```Notifiable``` trait, and sometimes (that's my case) chatIds are not related to a model.

What do you think!

**Comment by irazasyed** [comment]
You don't need a Model to send notifications.

Here's an example I just tested with multiple chat IDs:

```php
use Illuminate\Support\Facades\Notification;

Notification::send([$chatId1, $chatId2], new InvoicePaid());
```

```php
namespace App\Notifications;

use Illuminate\Notifications\Notification;
use NotificationChannels\Telegram\TelegramMessage;

class InvoicePaid extends Notification
{
    public function via($notifiable)
    {
        return ['telegram'];
    }

	public function toTelegram($notifiable)
    {
        $text = "This is a test notification!";

        return TelegramMessage::create()
            ->to($notifiable)
            ->content($text);
	}
}
```

**Comment by faissaloux** [comment]
@irazasyed Yes you r right thank you for the information!

So while we can do this, after your approval we can take this PR as another way of doing it as I wished to pass multiple chaIds to `to()` method and we can also benefice of the `sleep()` method that I added to avoid **rate limitations** with Telegram.

**Comment by irazasyed** [comment]
I appreciate the PR but this seems unnecessary at this time when we can already make use of the core features that are provided by Laravel including delaying/queuing features which give more control and flexibility than a specific channel level feature.

Thank you for the PR nonetheless.

**Pull request closed without merging**
