### PR TITLE
Add GitHub actions

### PR DESCRIPTION
**Pull request by alexsoft**
I guess actions themselves should be enabled in this repository, but I prepared two workflows:

1. run tests on different versions of php and with different flags (prefer-lowest and prefer-stable)
2. run tests on php 7.4 with coverage, as there is no need to execute coverage parts on all versions of php

### CODE REVIEW

**Comment by irazasyed** [comment]
Thanks for the PR. This was a much needed one. Appreciate it. 👍 

Could you also please add PHP 8 support?

**Comment by alexsoft** [comment]
@irazasyed, sure.
Which version should be used for coverage workflow then? 7.4 or 8.0?

**Comment by irazasyed** [comment]
8.0 is good.

**Comment by alexsoft** [comment]
@irazasyed done. I also took the liberty to allow phpunit 9 :)

**Comment by irazasyed** [comment]
I noticed that. Good, appreciated :)

Thanks!

**Comment by alexsoft** [comment]
@irazasyed There is still something wrong with scrutinizer, but I am not absolutely sure how to fix it

**Pull request merged**
